services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5004
    networks:
      - call-app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - call-app-network
    restart: unless-stopped

networks:
  call-app-network:
    driver: bridge
